### ISSUE TITLE
Beaglebone and host

### ISSUE THREAD

**Issue by kwsg97** [skerkour/kerkour.com#10]
I want to assign this between two parties Beagle bone black and my computer !  It works for that implementation?

**Comment by skerkour** [comment]
Hello,
Sorry I'm not sure to understand what you are talking about 😕

**Comment by kwsg97** [comment]
For the diffie helman key exchange , i want to set up the key exchange  end to end flow. I have my pc in linux and i have a beaglebone black connecting on ethernet with my pc. It is possible to use this keyexchange code for generate public and private keys and in the end generate a key secret ? . Finally i want to have a key exchange between two parties , two devices!

**Comment by skerkour** [comment]
Ho I see

It depends of your threat model. But in this scenario, I think that it's way simpler to only use symmetric encryption to encrypt data between the devices and put the same secret key on both your computer and Beaglebone.

DH Key exchange is more useful when the two (or more) parties need to communicate without having the occasion to exchange keys physically.

At the end of the day, key exchange's role is to establish a shared symmetric encryption key, so if you can completely skip key exchange step, you may as well do it.
