### ISSUE TITLE
Newsletter subscription doesn't work

### ISSUE THREAD

**Issue by BjoernPetersen** [skerkour/kerkour.com#13]
Hey, I'd be very interested in the weekly newsletter with your thoughts on complexity, hacking and entrepreneurship! Unfortunately, the subscribe button on kerkour.com doesn't seem to work.

**Comment by skerkour** [comment]
Thank you for the report!
The newsletter is temporarily paused.
In the mean time I can manually add you to the list, so feel free to send me your email in the red chatbox at the bottom right of the https://kerkour.com/about page :)
