### ISSUE TITLE
Scans beyond TCP connect

### ISSUE THREAD

**Issue by David-OConnor** [skerkour/kerkour.com#13]
Hi! Would this code base be modifiable to support other scan types, for example a Syn scan? My suspicions are you would need a very different approach, since `std::net` and `tokio::net` don't give you control over this. (Maybe the `socket2` lib?), but I'm curious.

**Comment by skerkour** [comment]
Hi @David-OConnor,

I'm not sure about the low-level library to use specifically for a Syn scan, but the in term of architecture, it would be really simple to adapt.

Either by using [trait objects](https://doc.rust-lang.org/book/ch17-02-trait-objects.html) and wrapping each scanning method in a different type,

or simply by wrapping (if needed) the blocking call for Syn Scan in with tokio's [spawn_blocking](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html)

✌️
