### ISSUE TITLE
Error: Decrypting large file: aead::Error routine

### ISSUE THREAD

**Issue by HelixTP** [skerkour/kerkour.com#40]
Hello
I found a small error or omission in the decryption function, you forgot to add 16 bytes to BUFFER_LEN (based or you other code to [encrypt file](https://kerkour.com/rust-file-encryption)

`const BUFFER_LEN: usize = 500; `

to

`const BUFFER_LEN: usize = 500 + 16; `

**Comment by skerkour** [comment]
Hello, thank you for the feedback!

What portion of the code are you talking about? Please provide a link to the file, because at least here: https://github.com/skerkour/kerkour.com/blob/main/2021/rust_file_encryption/src/main.rs `const BUFFER_LEN: usize = 500 + 16;` seems correct.

**Comment by HelixTP** [comment]
Hello, 
At line 126, in the main.r file. 

But in the code of the blog the error is not there.

**Comment by skerkour** [comment]
Line 126? https://github.com/skerkour/kerkour.com/blob/80f17624b1708b2ce9620af2a352afd92cae13cc/2021/rust_file_encryption/src/main.rs#L126

**Comment by HelixTP** [comment]
Non, in [rust_file_encryption_with_password](https://github.com/skerkour/kerkour.com/blob/main/2022/rust_file_encryption_with_password/src/main.rs)

**Comment by skerkour** [comment]
Thanks!

It's now fixed :)
