### ISSUE TITLE
Registry Expiry Date: 2030-04-16T17:02:18Z

### ISSUE THREAD

**Issue by stappersg** [skerkour/kerkour.com#95]
Hello,

Last week I encountered `Forbidden` when visiting https://kerkour.com with a webbrowser.

It is reproducible from the command line: 
```text
$ curl --silent  https://kerkour.com
Forbidden
$
```

Today I digged deeper and found
```text
$ whois kerkour.com | head -n 8
   Domain Name: KERKOUR.COM
   Registry Domain ID: 2114873420_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.registrar.amazon.com
   Registrar URL: http://registrar.amazon.com
   Updated Date: 2024-01-09T11:52:21Z
   Creation Date: 2017-04-16T17:02:18Z
   Registry Expiry Date: 2030-04-16T17:02:18Z
   Registrar: Amazon Registrar, Inc.
```

With this issue is the expired  expiry date documented.

**Comment by vi** [comment]
The site seems to ban wide range of IP addresses, including [Internet Archive](web.archive.org) and a [downtime checker](https://downforeveryoneorjustme.com/). `robots.txt` does also seem restrictive.

Seems like viewing that site is a privilege, not right.

**Comment by stappersg** [comment]
Closing this issue (that I opened).   The
```text
$ curl --silent  https://kerkour.com
Forbidden
$
```
is still present. _Seems like viewing the site is a privilege for some webbrowsers, not a right for each HTTP client._ I could do reproduce the _"Using Firefox to access sites gives me HTTP 403 forbidden, I've tried google chrome and that works"_, **but not now**.
